### PR TITLE
Update KordEx and Gradle, pin to Java 13

### PR DESCRIPTION
**Pull request by gdude2002**
This PR introduces the following changes:

- Pin Java 13 as the compatible JDK version, as this is KordEx's minimum required Java version
- Update to KordEx v2, which is retrieved via the new Maven repo and has a different set of packages
- Update Gradle wrapper to 8.10

Nothing too complex in this one. Should I bump the version?

### CODE REVIEW

**Comment by NoComment1105** [comment]
Looks good, was `./gradlew wrapper --gradle-version=8.10` run? If not could it be run please? A minor version bump would be preferable please.

**Comment by NoComment1105** [comment]
Also, builds fail so could java 13 be set in the workflows please

**Comment by gdude2002** [comment]
Yep, the specific command was `./gradlew wrapper --gradle-version 8.10`

And sure thing, I'll get that sorted now.

**Comment by NoComment1105** [comment]
> Yep, the specific command was `./gradlew wrapper --gradle-version 8.10`
> 
> And sure thing, I'll get that sorted now.

Interesting, was expecting alterations to the batch file and gradlew file. Was it run twice? The second run makes a full update

**Comment by gdude2002** [comment]
It has to be run twice? TIL, but yep, that did do what you expected.

**Comment by NoComment1105** [comment]
Excellent, thanks waiting for checks to run then will merge

**Comment by NoComment1105** [comment]
Thanks!

**Pull request merged**
